---
- name: Config nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Config 00-nginx.conf
  template:
    src: 00-nginx.conf.j2
    dest: /etc/nginx/conf.d/00-nginx.conf

- name: Config default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Config php_fastcgi
  template:
    src: php_fastcgi.j2
    dest: /etc/nginx/php_fastcgi

- name: Config general snippet
  template:
    src: general.j2
    dest: /etc/nginx/general

- name: Config acme snippet
  template:
    src: acme.j2
    dest: /etc/nginx/acme

- name: Config security snippet
  template:
    src: security.j2
    dest: /etc/nginx/security

- name: Config proxy_ssl snippet
  template:
    src: proxy_ssl.j2
    dest: /etc/nginx/proxy_ssl

- name: Make dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/nginx/tls"
    - "/usr/share/nginx/acme-challenge"

- name: Nginx nolimit
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "nginx  soft  nofile  65535"
    - "nginx  hard  nofile  65535"

- name: Generate DHparam
  openssl_dhparam:
    path: /etc/nginx/tls/dhparam.pem
    size: 2048

- name: Generate self-signed private key
  openssl_privatekey:
    path: /etc/nginx/tls/self.key
    size: 2048

- name: Generate self-signed tls cert
  openssl_certificate:
    path: /etc/nginx/tls/self.crt
    privatekey_path: /etc/nginx/tls/self.key
    provider: selfsigned

- name: Nginx Service
  systemd:
    name: nginx.service
    state: started
    enabled: yes
