---
  - name: Install apt packages
    apt:
      name:
        - gnupg2
        - ca-certificates
  
  - name: Apt nginx signing key
    apt_key:
      url: https://nginx.org/keys/nginx_signing.key
      state: present
  
  - name: Add nginx/stable repository
    apt_repository:
      repo: "deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
      filename: nginx
  
  - name: Install nginx
    apt:
      name:
        - nginx
      state: present
      update_cache: yes
