---
- sysctl:
      name: net.core.rmem_max
      value: "16777216"

- sysctl:
      name: net.core.wmem_max
      value: "16777216"

- sysctl:
      name: net.core.somaxconn
      value: "4096"

- sysctl:
      name: net.core.default_qdisc
      value: "fq"

- sysctl:
      name: net.ipv4.tcp_congestion_control
      value: "bbr"

- sysctl:
      name: net.ipv4.ip_local_port_range
      value: "1024 65535"

- sysctl:
      name: net.ipv4.tcp_tw_reuse
      value: "1"

- sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: "1"

- sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: "0"

- sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: "1"

- sysctl:
      name: net.ipv4.tcp_timestamps
      value: "0"

- sysctl:
      name: net.ipv4.tcp_syncookies
      value: "1"

- sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: "4096"

- sysctl:
      name: net.ipv4.tcp_synack_retries
      value: "3"

- sysctl:
      name: net.ipv4.tcp_max_tw_buckets
      value: "1440000"

- sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: "1"
  when: not ipv6

- sysctl:
      name: net.ipv6.conf.default.disable_ipv6
      value: "1"
  when: not ipv6

- sysctl:
      name: net.ipv6.conf.lo.disable_ipv6
      value: "1"
  when: not ipv6

- sysctl:
      name: fs.file-max
      value: "100000"

- sysctl:
      name: vm.swappiness
      value: "1"

- sysctl:
      name: vm.dirty_ratio
      value: "15"

- sysctl:
      name: vm.dirty_background_ratio
      value: "5"
