---
- name: debug
  debug:
    msg: "{{ username }} {{ main_domain }} {{ alter_domains }} {{ le_email }} {{ db_name }}"

- name: check user is existed
  command: "id {{ username }}"
  register: checkuser
  ignore_errors: true

- name: create new user
  debug:
    msg: "Creating new user {{ username }}"
  when: checkuser is failed

- name: include create user task
  include_tasks: user_create.yml
  when: checkuser is failed

- name: re check user if is created
  command: "id {{ username }}"
  register: recheckuser
  ignore_errors: true

- name: create site
  include_tasks: site_create.yml
  when: recheckuser is succeeded
