---
- name: make docroot
  file:
    path: /home/{{ username }}/{{ main_domain }}
    owner: "{{ username }}"
    group: "www-data"
    state: directory
    mode: '770'

- name: add new database
  command: "mysql -u root -e \"CREATE SCHEMA `{{ username }}_{{ db_name }}` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\""
  when: db_name != ""

- name: vhost nginx conf
  template:
    src: "{{ 'vhost_tls' if le_email else 'vhost'  }}.conf.j2"
    dest: /etc/nginx/conf.d/{{ main_domain }}.conf

- name: nginx reload
  systemd:
    name: nginx
    state: reloaded

- name: setup TLS
  include_tasks: tls.yml
  when: le_email != ""
