---
- name: run LE to generate tls
  command: "/var/lego/lego.sh run {{ le_email }} {{ main_domain }}"

- name: replace tls path
  replace:
    path: /etc/nginx/conf.d/{{ main_domain }}.conf
    regexp: '/etc/nginx/tls/self\.(.+)'
    replace: '/var/lego/certificates/{{ main_domain }}.\1'

- name: nginx reload
  systemd:
    name: nginx
    state: reloaded

- name: add new domain to renew domain
  lineinfile:
    path: /var/lego/renew_domains.txt
    line: "{{ main_domain }}|{{ le_email }}"
