---
- name: Add ppa php
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP and PHP libs
  apt:
    name:
      - "php{{ php_ver | default ('7.4') }}-bz2"
      - "php{{ php_ver | default ('7.4') }}-cli"
      - "php{{ php_ver | default ('7.4') }}-common"
      - "php{{ php_ver | default ('7.4') }}-curl"
      - "php{{ php_ver | default ('7.4') }}-fpm"
      - "php{{ php_ver | default ('7.4') }}-gd"
      - "php{{ php_ver | default ('7.4') }}-intl"
      - "php{{ php_ver | default ('7.4') }}-mbstring"
      - "php{{ php_ver | default ('7.4') }}-mysql"
      - "php{{ php_ver | default ('7.4') }}-opcache"
      - "php{{ php_ver | default ('7.4') }}-readline"
      - "php{{ php_ver | default ('7.4') }}-xml"
      - "php{{ php_ver | default ('7.4') }}-xmlrpc"
      - "php{{ php_ver | default ('7.4') }}-xsl"
      - "php{{ php_ver | default ('7.4') }}-zip"
      - "php{{ php_ver | default ('7.4') }}-redis"

- name: Cli config
  template:
    src: 90-custom-cli.ini.j2
    dest: /etc/php/{{ php_ver | default ('7.4') }}/cli/conf.d/90-custom.ini

- name: FPM config
  template:
    src: 90-custom-fpm.ini.j2
    dest: /etc/php/{{ php_ver | default ('7.4') }}/fpm/conf.d/90-custom.ini

- name: PHPFPM Service
  systemd:
    name: php{{ php_ver | default ('7.4') }}-fpm.service
    state: restarted
    enabled: yes

- name: Download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Run script
  shell:
    chdir: /tmp
    cmd: /usr/bin/php composer-setup.php

- name: Copy composer to bin dir
  copy:
    remote_src: true
    src: /tmp/composer.phar
    dest: /usr/local/bin/composer

- name: Allow composer to run
  file:
    path: /usr/local/bin/composer
    mode: a+x
