---
- name: Add ppa php
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Install PHP and PHP libs
  apt:
    name:
      - "php{{ php_ver }}-bz2"
      - "php{{ php_ver }}-cli"
      - "php{{ php_ver }}-common"
      - "php{{ php_ver }}-curl"
      - "php{{ php_ver }}-fpm"
      - "php{{ php_ver }}-gd"
      - "php{{ php_ver }}-intl"
      - "php{{ php_ver }}-mbstring"
      - "php{{ php_ver }}-mysql"
      - "php{{ php_ver }}-opcache"
      - "php{{ php_ver }}-readline"
      - "php{{ php_ver }}-xml"
      - "php{{ php_ver }}-xmlrpc"
      - "php{{ php_ver }}-xsl"
      - "php{{ php_ver }}-zip"
      - "php{{ php_ver }}-redis"

- name: Cli config
  template:
    src: 90-custom-cli.ini.j2
    dest: /etc/php/{{ php_ver }}/cli/conf.d/90-custom.ini

- name: FPM config
  template:
    src: 90-custom-fpm.ini.j2
    dest: /etc/php/{{ php_ver }}/fpm/conf.d/90-custom.ini

- name: PHPFPM Service
  systemd:
    name: php{{ php_ver }}-fpm.service
    state: restarted
    enabled: yes

- name: Install Composer if not existed
  include: composer.yml
  when: "not '/usr/local/bin/composer' is exists"
