---
- name: Install MySQL
  command: apt install -y mysql-server mysql-client
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Mysql Server Config
  template:
    src: mysqld.conf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Restart Mysql Service
  systemd:
    name: mysql.service
    state: restarted
    enabled: yes

- name: Generate .my.cnf
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: '600'
  