---
- name: Install MySQL
  command: apt install -y mysql-server mysql-client
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: MySQL nolimit
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "mysql  soft  nofile  10000"
    - "mysql  hard  nofile  20000"

- name: Mysql Server Config
  template:
    src: mysqld.conf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Restart Mysql Service
  systemd:
    name: mysql.service
    state: restarted
    enabled: yes

- name: Generate .my.cnf
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: '600'

- name: Backup script
  template:
    src: mybackup.sh.j2
    dest: /usr/local/bin/mybackup
    mode: a+x

- name: Install rclone installer
  get_url:
    url: https://rclone.org/install.sh
    dest: /tmp/rclone_install.sh

- name: Run rclone installer
  shell:
    chdir: /tmp
    cmd: /usr/bin/bash rclone_install.sh
