---
- name: run LE to generate tls
  command: "/opt/lego/lego -a -k rsa2048 --path /var/lego --email {{ le_email }} --http --http.webroot=\"/usr/share/nginx/acme-challenge\" --domains {{ main_domain }} {{ (([''] + alter_domains.split(',')) | join(' --domains ')) if alter_domains else '' }} run"

- name: replace tls path
  replace:
    path: /etc/nginx/conf.d/{{ main_domain }}.conf
    regexp: '/etc/nginx/tls/self\.(.+)'
    replace: '/var/lego/certificates/{{ main_domain }}.\1'

- name: nginx reload
  systemd:
    name: nginx
    state: reloaded

- name: add new domain to renew domain
  lineinfile:
    path: /var/lego/renew_domains.txt
    line: "{{ main_domain }}|{{ le_email }}"
