---
- hosts: all
  vars_files:
    - vars/all.yml
  vars_prompt:
    - name: run_confirm
      prompt: >-
        You have selected {{ ansible_play_batch }}. Do you want
        to continue?
  roles:
    - confirm
    - linux
    - nginx_install
    - mysql_install
    - nodejs_install
    - redis_install
    - php_install